version: "3"

services:
  flarum_db:
    image: mysql:latest
    container_name: flarum_db
    environment:
      - MYSQL_ROOT_PASSWORD=flarum_8e1e5d43_5d22_af75_2413
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=flarum_8e1e5d43_5d22_af75_2413
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql
  flarum:
    image: flarum:1.7.0
    container_name: flarum
    environment:
      - DEBUG=false
      - FORUM_URL=http://localhost:8888/
      - DB_HOST=flarum_db
      - DB_NAME=flarum
      - DB_USER=flarum
      - DB_PASS=flarum_8e1e5d43_5d22_af75_2413
      - DB_PREF=flarum_
      - DB_PORT=3306
      - FLARUM_ADMIN_USER=admin
      - FLARUM_ADMIN_PASS=admin
      - FLARUM_ADMIN_MAIL=admin@domain.tld
      - FLARUM_TITLE=Flarum
      - PHP_EXTENSIONS=flarum-lang/chinese-simplified
    volumes:
      - /mnt/docker/flarum/assets:/flarum/app/public/assets
      - /mnt/docker/flarum/extensions:/flarum/app/extensions
      - /mnt/docker/flarum/storage/logs:/flarum/app/storage/logs
      - /mnt/docker/flarum/nginx:/etc/nginx/flarum
    ports:
      - 8888:8888
    depends_on:
      - flarum_db
